name: Feature Request
description: Suggest an idea for approvalprotocol
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature for approvalprotocol!
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
      placeholder: I think approvalprotocol should...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe alternatives you've considered
      placeholder: I also thought about...
    validations:
      required: false
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of approvalprotocol does this affect?
      options:
        - Protocol specification
        - Server implementation
        - Client implementation
        - Examples
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
